# Generated by Django 4.0.1 on 2022-01-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_proejct_link_event_tbl_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_tbl',
            name='deadline',
            field=models.DateField(),
        ),
    ]
