# Generated by Django 4.0.1 on 2022-01-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_tbl_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_tbl',
            old_name='project_link',
            new_name='poster_link',
        ),
    ]
