# Generated by Django 4.0 on 2022-01-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_tbl_poster_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='participant_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('conatct', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('event_name', models.CharField(max_length=30)),
                ('reg_type', models.CharField(max_length=15)),
                ('people', models.IntegerField()),
            ],
        ),
    ]
