# Generated by Django 4.0 on 2022-01-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_participant_tbl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant_tbl',
            old_name='conatct',
            new_name='contact',
        ),
    ]
