# Generated by Django 4.0 on 2022-01-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_rename_conatct_participant_tbl_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_tbl',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
